# This file is a template, and might need editing before it works on your project.
# Official framework image. Look for the different tagged releases at:
# https://hub.docker.com/r/library/python
image: python:3.6

# This folder is cached between builds
# http://docs.gitlab.com/ce/ci/yaml/README.html#cache
cache:
  paths:
  - ~/.cache/pip/

stages:
  - build

build:
  stage: build
  tags:
    - shared-fi
  before_script:
    - python -V                                   # Print out python version for debugging
    - pip install pipenv

  script:
    - pipenv install --dev
    - pipenv run coverage run -m pytest
